#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOF
  CREATE ROLE ${DATASTORE_READONLY_USER} NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '${DATASTORE_READONLY_PASSWORD}';
  CREATE DATABASE ${DATASTORE_DB} OWNER ${POSTGRES_USER} ENCODING 'utf-8';
  GRANT ALL PRIVILEGES ON DATABASE ${DATASTORE_DB} TO ${POSTGRES_USER};
EOF
